### PR TITLE
Update eagle-vocabulary-dating-criteria.rdf

### PR DESCRIPTION
**Pull request by Nicobette**
<skos:broader rdf:resource="https://www.eagle-network.eu/voc/dates/lod/109"/>
 		<dct:created>2015-01-15 01:00:00</dct:created>
 	</skos:Concept>
+	<skos:Concept rdf:about="https://www.eagle-network.eu/voc/dates/lod/110">
+		<skos:prefLabel xml:lang="en">IX AD</skos:prefLabel>
+		<skos:altLabel xml:lang="en">IX CE</skos:altLabel>
+		<skos:altLabel xml:lang="it">IX d.C.</skos:altLabel>
+		<skos:altLabel xml:lang="en">ninth century AD</skos:altLabel>
+		<skos:altLabel xml:lang="en">ninth century CE</skos:altLabel>
+		<skos:altLabel xml:lang="it">nono secolo d.C.</skos:altLabel>
+		<skos:scopeNote>0801 ; 0900</skos:scopeNote>
+	</skos:Concept>
+	<skos:Concept rdf:about="https://www.eagle-network.eu/voc/dates/lod/111">
+                <skos:prefLabel xml:lang="en">X AD</skos:prefLabel>
+		<skos:altLabel xml:lang="en">X CE</skos:altLabel>
+		<skos:altLabel xml:lang="it">X d.C.</skos:altLabel>
+		<skos:altLabel xml:lang="en">tenth century AD</skos:altLabel>
+		<skos:altLabel xml:lang="en">tenth century CE</skos:altLabel>
+		<skos:altLabel xml:lang="it">decimo secolo d.C.</skos:altLabel>
+		<skos:scopeNote>0901 ; 1000</skos:scopeNote>
+	</skos:Concept>
+	<skos:Concept rdf:about="https://www.eagle-network.eu/voc/dates/lod/112">
+                <skos:prefLabel xml:lang="en">XI AD</skos:prefLabel>
+		<skos:altLabel xml:lang="en">XI CE</skos:altLabel>
+		<skos:altLabel xml:lang="it">XI d.C.</skos:altLabel>
+		<skos:altLabel xml:lang="en">eleventh century AD</skos:altLabel>
+		<skos:altLabel xml:lang="en">eleventh century CE</skos:altLabel>
+		<skos:altLabel xml:lang="it">undicesimo secolo d.C.</skos:altLabel>
+		<skos:scopeNote>1001 ; 1100</skos:scopeNote>

### CODE REVIEW

**Comment by PietroLiuzzo** [comment]
@Nicobette thanks for this PR!
Could you please document briefly here why you made those additions? were these centuries simply missing?

**Comment by Nicobette** [comment]
@PietroLiuzzo Indeed, the reason is that these centuries were missing (and I needed them), and I thought it would be a good idea to extend the dating criteria up to the eleventh century.

**Comment by Nicobette** [comment]
@PietroLiuzzo Can the new criteria already be used?
Also, would you mind me adding a few more criteria (in particular, the Byzantine period)?

**Comment by PietroLiuzzo** [comment]
You are most welcome!
unfortunately this relies on my spare time, I will make sure they are available via the website as soon as possible. if you do this other additions, even better, I will then wait for that.

**Comment by Nicobette** [comment]
@PietroLiuzzo It's done. I added the Byzantine period, and that's it for now.

**Pull request merged**
