### PR TITLE
First attempt at fix the mixed-content problems

### PR DESCRIPTION
**Pull request by adellam**
This batch changes a lot of URLs that generate mixed-content errors
when requested from a site with https enabled.

More remain, all of the form http://www.eagle-network.eu/
I’m not sure if they need to be fixed.

### CODE REVIEW

**Comment by PietroLiuzzo** [comment]
So, you changed the xslt and run it again to update all the files and then committed those in this PR? sorry, just to make sure.

**Comment by PietroLiuzzo** [comment]
I think one way to be sure things are https everywhere, would be to updated the source files in this direction.

**Comment by adellam** [comment]
No, I first changed the 2000+ files using grep and sed. Only after reading your last email I understood how they are generated, so I changed the xslt too.
Maybe it's better if you generate the contents again after accepting the pull request.

**Comment by PietroLiuzzo** [comment]
I can merge your request, basically not to redo the substitutions in the xslt. then I will update the source files and run the xslt again to produce the output. there should then be no more http

**Comment by PietroLiuzzo** [comment]
done

**Pull request merged**
